#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VSOTeams.Droid.Resource", IsApplication=true)]

namespace VSOTeams.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::VSOTeams.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::VSOTeams.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buildcompletedevent = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkinevent = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Failed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int House = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Login = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monoandroidsplash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int part = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int prj = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int refresh = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int room = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int slideout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Stopped = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int succes = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int workitemchangedevent = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
